// Code generated by github.com/Bin-Huang/newc; DO NOT EDIT.

package errors

// NewForbidden Create a new Forbidden
func NewForbidden(msg string) Forbidden {
	s := Forbidden{
		Msg: msg,
	}
	s.init()
	return s
}
