// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.
// Code generated at 2022-07-24T23:11:40+08:00.

package pkg1

import (
	"fmt"

	"io"

	. "os"

	stringutils "strings"
)

// NewService Create a new Service
func NewService(name string) *Service {
	return &Service{
		Name: name,
	}
}

// NewPostService Create a new PostService
func NewPostService(service Service, version int) *PostService {
	return &PostService{
		Service: service,
		Version: version,
	}
}

// NewAgeService Create a new AgeService
func NewAgeService(service Service, age int, writer io.Writer, file File, aa stringutils.Builder, stringer fmt.Stringer) *AgeService {
	return &AgeService{
		Service:  service,
		Age:      age,
		Writer:   writer,
		File:     file,
		AA:       aa,
		Stringer: stringer,
	}
}
