// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.

package services

// NewBaseService Create a new baseService
func NewBaseService(debugLevel int) *baseService {
	return &baseService{
		debugLevel: debugLevel,
	}
}
