// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.
// Code generated at 2022-07-24T23:10:41+08:00.

package services

// NewBaseService Create a new baseService
func NewBaseService(debugLevel int) *baseService {
	return &baseService{
		debugLevel: debugLevel,
	}
}
