// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.

package services

import (
	"log"

	"github.com/Bin-Huang/make-constructor/test/repositories"
)

// NewEmailService Create a new EmailService
func NewEmailService(baseService baseService, userRepository *repositories.UserRepository, logger *log.Logger) *EmailService {
	return &EmailService{
		baseService:    baseService,
		userRepository: userRepository,
		logger:         logger,
	}
}
