// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.
// Code generated at 2022-07-24T23:11:47+08:00.

package services

import (
	"log"

	"github.com/Bin-Huang/make-constructor/test/repositories"
)

// NewUserService Create a new UserService
func NewUserService(baseService baseService, userRepository *repositories.UserRepository, proRepository *repositories.ProRepository, emailService *EmailService, logger *log.Logger, debug bool) *UserService {
	return &UserService{
		baseService:    baseService,
		userRepository: userRepository,
		proRepository:  proRepository,
		emailService:   emailService,
		logger:         logger,
		debug:          debug,
	}
}
