// Code generated by github.com/Bin-Huang/newc; DO NOT EDIT.

package unittest

// NewStructRef Create a new StructRef
func NewStructRef(debug bool) *StructRef {
	return &StructRef{
		Debug: debug,
	}
}

// NewStructValue Create a new StructValue
func NewStructValue(debug bool) StructValue {
	return StructValue{
		Debug: debug,
	}
}

// NewStructWithInit Create a new StructWithInit
func NewStructWithInit(debug bool) *StructWithInit {
	s := &StructWithInit{
		Debug: debug,
	}
	s.init()
	return s
}

// NewStructValueWithInit Create a new StructValueWithInit
func NewStructValueWithInit(debug bool) StructValueWithInit {
	s := StructValueWithInit{
		Debug: debug,
	}
	s.init()
	return s
}
