// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.

package repositories

import (
	"time"

	"github.com/Bin-Huang/make-constructor/test/config"
)

// NewDatabase Create a new database
func NewDatabase(dsn string, timeout time.Duration, debug bool) *database {
	return &database{
		DSN:     dsn,
		Timeout: timeout,
		debug:   debug,
	}
}

// NewProRepository Create a new ProRepository
func NewProRepository(conf config.Config, db *database, tableName string, version int) *ProRepository {
	return &ProRepository{
		conf:      conf,
		db:        db,
		TableName: tableName,
		version:   version,
	}
}

// NewUserRepository Create a new UserRepository
func NewUserRepository(conf *config.Config, db *database, tableName string) *UserRepository {
	return &UserRepository{
		conf:      conf,
		db:        db,
		TableName: tableName,
	}
}
