// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.
// Code generated at 2022-07-24T23:10:38+08:00.

package repositories

import (
	"time"
)

// NewDatabase Create a new database
func NewDatabase(dsn string, timeout time.Duration, debug bool) *database {
	return &database{
		DSN:     dsn,
		Timeout: timeout,
		debug:   debug,
	}
}
