// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.
// Code generated at 2022-07-24T23:11:45+08:00.

package repositories

// NewProRepository Create a new ProRepository
func NewProRepository(db *database, tableName string, version int) *ProRepository {
	return &ProRepository{
		db:        db,
		TableName: tableName,
		version:   version,
	}
}
