// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.

package repositories

// NewProRepository Create a new ProRepository
func NewProRepository(db *database, tableName string, version int) *ProRepository {
	return &ProRepository{
		db:        db,
		TableName: tableName,
		version:   version,
	}
}
