// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.
// Code generated at 2022-07-24T23:10:38+08:00.

package repositories

// NewUserRepository Create a new UserRepository
func NewUserRepository(db *database, tableName string) *UserRepository {
	return &UserRepository{
		db:        db,
		TableName: tableName,
	}
}
