// Code generated by github.com/Bin-Huang/make-constructor; DO NOT EDIT.

package repositories

// NewUserRepository Create a new UserRepository
func NewUserRepository(db *database, tableName string) *UserRepository {
	return &UserRepository{
		db:        db,
		TableName: tableName,
	}
}
